export const departamentos = [
  'Amazonas',
  'Antioquia',
  'Arauca',
  'Atlántico',
  'Bogotá',
  'Bolívar',
  'Boyacá',
  'Caldas',
  'Caquetá',
  'Casanare',
  'Cauca',
  'Cesar',
  'Chocó',
  'Córdoba',
  'Cundinamarca',
  'Guainía',
  'Guaviare',
  'Huila',
  'La Guajira',
  'Magdalena',
  'Meta',
  'Nariño',
  'Norte de Santander',
  'Putumayo',
  'Quindío',
  'Risaralda',
  'San Andrés e Providencia',
  'Santander',
  'Sucre',
  'Tolima',
  'Valle del Cauca',
  'Vaupés',
  'Vichada',
];

export const dichos = [
  'Soldado advertido no muere en guerra',
  'De eso tan bueno no dan tanto',
  'Dime con quién andas, y te diré quién eres',
  'A caballo regalado no se le mira el colmillo',
  'No me abra los ojos que no le voy a echar gotas',
  'Mugre que no mata, engorda',
  'A mal tiempo, buena cara',
  'A palabras necias, oídos sordos',
  'Al que le van a dar, le guardan',
  'Cuando el río suena, piedras lleva',
  'Se acomoda más que un desvelado',
  'Le cuento el milagro pero no el santo',
  'Más feo que un carro por debajo',
  'Tengo un filo, que si me agacho me corto',
  'Le falta pelo pa` moña',
  'Cuentas claras y el chocolate espeso',
  'Si así fuera, otro gallo cantara',
  'Puya el burro',
  'Más bullero que loro mojao',
  'Aguanta el burro',
  'No dar papaya',
];

export const platos = [
  'Arepa',
  'Ajiaco',
  'Sancocho',
  'Tamale',
  'Empanada',
  'Pan de yuca',
  'Bandejap Paisa',
  'Lechona',
  'Changua',
  'Fritanga',
  'Hormigas culonas',
  'Rondón',
  'Pandebono',
  'Mamona',
  'Arroz de lisa',
  'Cuchuco',
  'Caldo de costilla',
  'Oblea',
  'Sudado de pollo',
  'Cazuela de mariscos',
  'Sobrebarriga',
  'Criollitos',
  'Pechuga ala plancha',
  'Picada',
  'Arroz con pollo',
  'Ensalada de frutas',
  'Crema de calabaza',
  'Cafe con pan',
  'Frijolada',
];
